# Use the official image as a parent image
# FROM mcr.microsoft.com/dotnet/sdk:8.0
FROM ghcr.io/shimat/opencvsharp/ubuntu22-dotnet6-opencv4.7.0:20230114

# Set the working directory
WORKDIR /workspace

# Copy the current directory contents into the container at /workspace
COPY . /workspace

# Install cURL and wget
RUN apt-get update && apt-get install -y curl
RUN apt-get update && apt-get install -y wget

# NET 8
RUN apt-get update && apt-get install -y dotnet-sdk-8.0

# NET 9
RUN wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh 
RUN chmod +x ./dotnet-install.sh
RUN ./dotnet-install.sh --version latest

RUN echo 'dotnet installation done!'
RUN dotnet --version

# # Install the .NET workloads
RUN dotnet workload update
RUN dotnet workload install aspire

# install Azure CLI
# RUN curl -L https://aka.ms/InstallAzureCli | bash

# Expose ports
# EXPOSE 5000
# EXPOSE 5001

# Define the entry point for the container
CMD ["dotnet", "run"]